services:
  microserviceapplication:
    image: microserviceapplication
    build:
      context: .
      dockerfile: MicroserviceApplication/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"  